server:
  port: 5005
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_database2
    username: root
    password: Ravi@6886
  jpa:
     show-sql: true
     hibernate:
      ddl-auto: update
     properties:
        hibernate:
         dialect: org.hibernate.dialect.MySQLDialect
    
